package com.xo.mapper;

import com.xo.model.TbSyncLog;
import com.xo.model.TbSyncLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSyncLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    long countByExample(TbSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    int deleteByExample(TbSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    int insert(TbSyncLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    int insertSelective(TbSyncLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    List<TbSyncLog> selectByExample(TbSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    TbSyncLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbSyncLog record, @Param("example") TbSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbSyncLog record, @Param("example") TbSyncLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbSyncLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbSyncLog record);
}