package com.xo.mapper;

import com.xo.model.Xo;

public interface XoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xo
     *
     * @mbg.generated
     */
    int insert(Xo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xo
     *
     * @mbg.generated
     */
    int insertSelective(Xo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xo
     *
     * @mbg.generated
     */
    Xo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Xo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Xo record);
}