package com.xo.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_sync_log
 */
public class TbSyncLog implements Serializable {
    private Long id;

    @ApiModelProperty(value = "日期")
    private Long dateNo;

    @ApiModelProperty(value = "时间段")
    private Integer time;

    @ApiModelProperty(value = "记录数")
    private Long recordCnt;

    @ApiModelProperty(value = "类型1.爬取 2api同步 3御善房")
    private Integer type;

    @ApiModelProperty(value = "表名")
    private String tableName;

    @ApiModelProperty(value = "环比")
    private Double linkRatio;

    @ApiModelProperty(value = "1、正常 2、告警")
    private Integer state;

    @ApiModelProperty(value = "状态：0未开始 1进行中 2成功 -1失败")
    private Integer status;

    @ApiModelProperty(value = "开始时间")
    private Date startTime;

    @ApiModelProperty(value = "结束时间")
    private Date endTime;

    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.id
     *
     * @return the value of tb_sync_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.id
     *
     * @param id the value for tb_sync_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.date_no
     *
     * @return the value of tb_sync_log.date_no
     *
     * @mbg.generated
     */
    public Long getDateNo() {
        return dateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.date_no
     *
     * @param dateNo the value for tb_sync_log.date_no
     *
     * @mbg.generated
     */
    public void setDateNo(Long dateNo) {
        this.dateNo = dateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.time
     *
     * @return the value of tb_sync_log.time
     *
     * @mbg.generated
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.time
     *
     * @param time the value for tb_sync_log.time
     *
     * @mbg.generated
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.record_cnt
     *
     * @return the value of tb_sync_log.record_cnt
     *
     * @mbg.generated
     */
    public Long getRecordCnt() {
        return recordCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.record_cnt
     *
     * @param recordCnt the value for tb_sync_log.record_cnt
     *
     * @mbg.generated
     */
    public void setRecordCnt(Long recordCnt) {
        this.recordCnt = recordCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.type
     *
     * @return the value of tb_sync_log.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.type
     *
     * @param type the value for tb_sync_log.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.table_name
     *
     * @return the value of tb_sync_log.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.table_name
     *
     * @param tableName the value for tb_sync_log.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.link_ratio
     *
     * @return the value of tb_sync_log.link_ratio
     *
     * @mbg.generated
     */
    public Double getLinkRatio() {
        return linkRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.link_ratio
     *
     * @param linkRatio the value for tb_sync_log.link_ratio
     *
     * @mbg.generated
     */
    public void setLinkRatio(Double linkRatio) {
        this.linkRatio = linkRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.state
     *
     * @return the value of tb_sync_log.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.state
     *
     * @param state the value for tb_sync_log.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.status
     *
     * @return the value of tb_sync_log.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.status
     *
     * @param status the value for tb_sync_log.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.start_time
     *
     * @return the value of tb_sync_log.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.start_time
     *
     * @param startTime the value for tb_sync_log.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.end_time
     *
     * @return the value of tb_sync_log.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.end_time
     *
     * @param endTime the value for tb_sync_log.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sync_log.create_time
     *
     * @return the value of tb_sync_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sync_log.create_time
     *
     * @param createTime the value for tb_sync_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbSyncLog other = (TbSyncLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDateNo() == null ? other.getDateNo() == null : this.getDateNo().equals(other.getDateNo()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getRecordCnt() == null ? other.getRecordCnt() == null : this.getRecordCnt().equals(other.getRecordCnt()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getTableName() == null ? other.getTableName() == null : this.getTableName().equals(other.getTableName()))
            && (this.getLinkRatio() == null ? other.getLinkRatio() == null : this.getLinkRatio().equals(other.getLinkRatio()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDateNo() == null) ? 0 : getDateNo().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getRecordCnt() == null) ? 0 : getRecordCnt().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getTableName() == null) ? 0 : getTableName().hashCode());
        result = prime * result + ((getLinkRatio() == null) ? 0 : getLinkRatio().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sync_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dateNo=").append(dateNo);
        sb.append(", time=").append(time);
        sb.append(", recordCnt=").append(recordCnt);
        sb.append(", type=").append(type);
        sb.append(", tableName=").append(tableName);
        sb.append(", linkRatio=").append(linkRatio);
        sb.append(", state=").append(state);
        sb.append(", status=").append(status);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}